- name: Deploy Flask Fitness App
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/derOli101/CloudComputing2.git"
    app_dir: "/home/azureuser/flask-app"

  tasks:
    - name: Update APT cache & install dependencies
      apt:
        update_cache: yes
        name:
          - git
          - python3
          - python3-pip

    - name: Clone Flask App from Git
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main

    - name: Install Python requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        executable: pip3

    - name: Copy systemd service file
      copy:
        src: flask-app.service
        dest: /etc/systemd/system/flask-app.service
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Flask app
      systemd:
        name: flask-app
        enabled: yes
        state: started
